### ISSUE TITLE
Out-of-focus event for area inside `CodeWrapper`

### ISSUE THREAD

**Issue by trewjames** [trewjames/sourcetype#10]

**Comment by trewjames** [comment]
My bad, I didn't see this being assigned to you. I was just looking around at first and ended up implementing some changes.

It's pretty monkeytype-esque now except clicking into focus while it's already in focus is buggy.

**Comment by trewjames** [comment]
https://github.com/testing-library/jest-dom/discussions/394

> The input has autoFocus enabled, so it is understandable that it has focus. Can you try without autoFocus to see if it works?
> 
> Though I'd add this: even though fireEvent.click(codeInput) is too low level and won't actually set focus on the input, in real life if you click on the input element, that'll also set focus on the input. So the situation you're describing in your test has multiple angles through which the input should end up having focus. I wonder why you so adamantly expect it not to have focus. thinking
> 
> And last but not least, I suggest you use userEvent.click(codeInput) instead of fireEvent.click(codeInput). It's on a separate library though. Check it out: https://github.com/testing-library/user-event

**Comment by trewjames** [comment]
^ fixed an issue with one of the tests for out of focus being broken.
The clicking into focus while already in focus issue still persists.

**Comment by mineugene** [comment]
Looks and performs nicely!

Since we are comparing to Monkeytype, they have the same issue. They just alleviate it with some sort of timeout before invoking the out-of-focus feedback element. Hold the mouse press over the play area, and after 1000ms the out-of-focus warning appears.

I can implement this sometime today, if you'd like.

**Comment by mineugene** [comment]
Instant feedback would be preferable. Do you have any alternate ideas?

**Comment by trewjames** [comment]
Yeah instant feedback would be preferable but I don't really have any good ideas atm...
Maybe implement the monkeytype solution for now unless you can come up with something

**Comment by trewjames** [comment]
I think we can close this issue now no?

**Comment by trewjames** [comment]
actually did you see this? I just noticed this now. the test is passing, just I guess it's not an ideal test.
![image](https://user-images.githubusercontent.com/66286082/130307113-a9c6f4de-82a3-4e2c-a062-01d2a1ac66a8.png)

**Comment by mineugene** [comment]
I saw it and tried several things, but couldn't get anything done to make the test happy. Not sure what `act()` even does.
Probably leave the issue open until we get it sorted out.

**Comment by trewjames** [comment]
I got the test passing w/ no console errors with:
``` tsx
    userEvent.click(focusWarning);
    await waitFor(() => {
      expect(codeInput).not.toHaveFocus();
      expect(focusWarning).not.toHaveClass("hidden");
      expect(codeWrapper).toHaveClass("blurred");
    });
```
but github actions straight up fails the test...

**Comment by trewjames** [comment]
that's right bitch ass gh actions

**Comment by mineugene** [comment]
wp
