### ISSUE TITLE
Handle `Enter` key from input

### ISSUE THREAD

**Issue by trewjames** [trewjames/sourcetype#12]
- [x] don't send "Enter" to output
- [x] jump to new line
- [x] handle auto indentation if necessary
- [x] prevent jump to new line mid line
- [x] backspace behavior after new line (with and without indentation)
- [x] handle multiple indents (currently only indents once)

**Comment by mineugene** [comment]
> btw #12 is pretty hard

Do you want some help with one of the list items?

**Comment by trewjames** [comment]
yeahh... after I eat, I'll commit and push to the enter-input branch I have open for it.
I'll have to update the list of tasks. It's a little bit more complicated than just three items lol.

**Comment by trewjames** [comment]
also sorry but I renamed a few functions. Some of them where named unintuitively imo (eg docstring would say 'gets the current word being typed' but the function would be called getLastTyped so I think I changed that particular one to `getCurrentType`) or I wanted to create more distinction between functions manipulating `typed: Typed` and `word: string[][]`.

**Comment by mineugene** [comment]
> also sorry but I renamed a few functions. Some of them where named unintuitively imo (eg docstring would say 'gets the current word being typed' but the function would be called getLastTyped so I think I changed that particular one to `getCurrentType`) or I wanted to create more distinction between functions manipulating `typed: Typed` and `word: string[][]`.

No worries. My thought was of the array of words as a whole, and getting the last word from it; hence, `getLastWord`. Also, it was because I thought of the name after writing `bisectWord`. `getCurrentTyped` is a better name since it's referring to the current state.

**Comment by mineugene** [comment]
I will work on the backspace behaviour today
