### ISSUE TITLE
cursor misalignment when space mid word

### ISSUE THREAD

**Issue by trewjames** [trewjames/sourcetype#20]
when you hit space mid-word, the current word jumps to the next word which is fine but the cursor doesn't follow.

![image](https://user-images.githubusercontent.com/66286082/129502790-431fb573-bb2a-45d9-9f10-aca93ce482c7.png)
in the ss, I hit space mid way through `lazy` and fully typed `dog` but the cursor is still at the start of `dog`

**Comment by mineugene** [comment]
Note: changed font size in commit 95c0398 with tailwind style `text-2xl` to roughly re-align cursor.
