### ISSUE TITLE
offload smartsplitting to codeWrapper parent component

### ISSUE THREAD

**Issue by trewjames** [trewjames/sourcetype#24]
smartSpliting and anywhere in codeWrapper where `codeBlock` is being split and manipulated should probably be moved outside of codeWrapper. 

Currently, any key input re-renders codeWrapper entirely so moving those processes out of codeWrapper should help performance, particular when `codeBlock` actually start containing bigger snippets.

**Comment by mineugene** [comment]
I agree. There are several functions that need an indexed `codeBlock` to compare the current `typed` progress. Having a static resource that represents the `codeBlock` with a similar/identical data struct to `Typed` would make comparisons a lot easier. And ofc, having it as a helper outside CodeWrapper would be ideal for performance.

All functions that are involved with updating state from `<input>` need such resource: `getNextTyped()` and `getCursorMovement()`
