### ISSUE TITLE
Incorrectly typing letter shows correct letter in red

### ISSUE THREAD

**Issue by trewjames** [trewjames/sourcetype#8]
eg. typing `T` when supposed to type `a` will result in `a` being typed in red

**Comment by mineugene** [comment]
What is the expected behaviour?

**Comment by trewjames** [comment]
I think showing the actually typed letter. In this case `T` in red.

**Comment by mineugene** [comment]
Id actually prefer the correct letter shown with colour being the sole indication for correctness so that I know what letter it should be when I go back to correct it.
Other websites seem to follow either way. Maybe we can have a toggle for which behaviour the user wants?

**Comment by trewjames** [comment]
Oh yeah you're right. I thought it was the other way around on monkeytype.

**Comment by mineugene** [comment]
Do u want to make that behaviour a feature?
